# Generated by Django 4.2.7 on 2023-11-27 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdeskapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_user',
            field=models.ManyToManyField(related_name='softdesk_contributors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_project',
            field=models.ManyToManyField(related_name='softdesk_contributors', to='softdeskapi.project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Elevee')], max_length=32, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('A FAIRE', 'A faire'), ('EN COURS', 'En cours'), ('TERMINE', 'Termine')], max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'Bug'), ('AMELIORATION', 'Amelioration'), ('TACHE', 'Tache')], max_length=32, verbose_name='Balise'),
        ),
    ]
