# Generated by Django 4.2.7 on 2024-01-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdeskapi', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
