# Generated by Django 4.2.7 on 2024-01-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdeskapi', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_day',
            new_name='birthdate',
        ),
    ]
